### ISSUE TITLE
[feature request] hold shift to active

### ISSUE THREAD

**Issue by kreezxil** [ianwijma/stare-till-they-grow#12]
Have it require holding shift to activate the application of bone meal, default option to false so that it conforms to what your users expect.

**Comment by ianwijma** [comment]
I like it! I will probably work on it this weekend. 

I will make it probably into a config option. So it can be controlled by modpack devs.


Thanks!

**Comment by kreezxil** [comment]
yes that was what I thought i had suggested.thanks much.

**Comment by ianwijma** [comment]
@kreezxil  I have added the config option and it will be available [here](https://www.curseforge.com/minecraft/mc-mods/stare-till-they-grow/files/3269123) once its processed

**Comment by ianwijma** [comment]
Thanks again for the idea!

**Comment by kreezxil** [comment]
Thank you for adding it!
