### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Cynix32** [ianwijma/stare-till-they-grow#13]
GraalVM Java 8
Forge 36.1.4
MC 1.16.5

staretilltheygrow-1.16.5-1.0.4.jar

Console spams the following when playing. Otherwise the gameplay is normal.

`[Render thread/INFO] [STDOUT/]: [dev.tmp.StareTillTheyGrow.EventHandlers.PlayerEventHandlers:lookedAtGrowableEvent:33]: Looking at block`

**Comment by ianwijma** [comment]
First off. Thanks for reporting this bug! 

Second of all, I will fix this one as soon as I've time, thanks!

**Comment by ianwijma** [comment]
@Cynix32 I have fixed the issue and push a build with it fixed! It will be available [here](https://www.curseforge.com/minecraft/mc-mods/stare-till-they-grow/files/3269123) once its processed
