### ISSUE TITLE
Misnamed item in default blacklist.

### ISSUE THREAD

**Issue by malSet** [ianwijma/stare-till-they-grow#15]
Rather simple issue.

The default blacklist is (presumably) meant to disable the effect on Grass blocks.
`blackList = ["minecraft:grass"]`

However, the actually internal block name for Grass is `minecraft:grass_block`.

Changing this (`blackList = ["minecraft:grass_block"]`) results in the intended behaviour.

**Comment by ianwijma** [comment]
Thanks for such a sharp eye! 

I think both should be there. Grass and grass block. I will check if I need to update the default blacklist with other items. I will do them when I have time! 


Again thanks!
