### ISSUE TITLE
Crash while staring at cocoa beans on server.

### ISSUE THREAD

**Issue by kreezxil** [ianwijma/stare-till-they-grow#16]
server crash report: http://paste.ubuntu.com/p/n6rZB32z8P/
latest.log: http://paste.ubuntu.com/p/VnGssk5tSt/

**Comment by ianwijma** [comment]
Thanks for your report! 

I will check this one out during the weekend when possible.

**Comment by ianwijma** [comment]
Did some research, found out this issue is also present on singleplayer.

**Comment by ianwijma** [comment]
@kreezxil Fix pushed and uploaded @ https://www.curseforge.com/minecraft/mc-mods/stare-till-they-grow/files/3432920
